### ISSUE TITLE
[Frontend] HERE Maps config should be read from project configuration file

### ISSUE THREAD

**Issue by RaduCStefanescu** [code4romania/seismic-risc#178] opened 2020-03-05 14:29 UTC
The HERE Maps configuration should be read from the project configuration file.
The configuration is read at build time, and we should have at least 3 configurations available:
- local - for local development
- development - for the development environment
- production - for the live deployment

**Comment by tudoramariei** [comment] 2020-03-05 15:02
Closing as it's a duplicate of #151

**Closed by tudoramariei** 2020-03-05 15:02 UTC
Labels: duplicate
