### ISSUE TITLE
Implement new overlay for building display

### ISSUE THREAD

**Issue by catileptic** [code4romania/seismic-risc#704] opened 2021-08-09 20:13 UTC
When we click on a building, an overlay opens up over the map. The overlay currently looks like this:
![image](https://user-images.githubusercontent.com/14028425/128764694-5b6839b7-782c-40d7-a3d9-ba9d4321a365.png)

The [prototype in Figma](https://www.figma.com/file/dUL9ybnag2LhQpicJseFaH/Seismic-Risk?node-id=2066%3A2458) contains the updated version of this display. 

The Figma prototype is missing a close button. It should be in the upper-right corner, as an "X" icon, the same color as the title. 

The "vezi imagini" link should only show up if the building has any images attached to it. 

If the buildings has any images attached to it, clicking the link should display a modal view where the user can view each image and navigate among them using the left and right arrows on their keyboard, or left and right arrow buttons inside the modal view. 

On mobile, the elements in this panel should all be stacked on one column.
![image](https://user-images.githubusercontent.com/14028425/128764607-10b9f75b-6d3b-45fc-8607-a1ba6e09bcbc.png)

**Comment by CatalinCsnMaster** [comment] 2021-08-12 15:38
Hello! Can I take this one? 🙂

**Comment by tudoramariei** [comment] 2021-08-17 09:09
Sorry, @CatalinCsnMaster but this is a duplicate of #660 which is already taken
So I'll be closing this issue and any missing info will be transferred to the other issue

**Closed by tudoramariei** 2021-08-17 09:09 UTC
Labels: help wanted, client: ReactJS
